version: "3.9"

volumes:
  sockets:

services:
  lb:
    image: haproxy:lts-alpine
    cpus: "0.1"
    mem_limit: "30m"

    ports:
      - "9999:9999"

    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
      - sockets:/sockets:ro

    depends_on:
      - api1
      - api2
    restart: unless-stopped
    security_opt:
      - seccomp:unconfined
    ulimits:
      nofile:
        soft: 65535
        hard: 65535

  api1:
    build: .
    hostname: api1

    cpus: "0.45"
    mem_limit: "160m"

    environment:
      SOCKET_PATH: /sockets/api1.sock
    volumes:
      - sockets:/sockets
    restart: unless-stopped
    security_opt:
      - seccomp:unconfined
    ulimits:
      nofile:
        soft: 65535
        hard: 65535

  api2:
    build: .
    hostname: api2

    cpus: "0.45"
    mem_limit: "160m"

    environment:
      SOCKET_PATH: /sockets/api2.sock
    volumes:
      - sockets:/sockets
    restart: unless-stopped
    security_opt:
      - seccomp:unconfined
    ulimits:
        nofile:
          soft: 65535
          hard: 65535
